### ISSUE TITLE
require is failed on Windows

### ISSUE THREAD

**Issue by kou** [paddor/czmq-ffi-gen#7]
`require "czmq-ffi-gen"` is failed with the following backtrace:

```text
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ffi-1.9.14-x64-mingw32/lib/ffi/types.rb:69:in `find_type': unable to resolve type 'uint64_t' (TypeError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ffi-1.9.14-x64-mingw32/lib/ffi/library.rb:535:in `find_type'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ffi-1.9.14-x64-mingw32/lib/ffi/library.rb:267:in `block in attach_function'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ffi-1.9.14-x64-mingw32/lib/ffi/library.rb:254:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ffi-1.9.14-x64-mingw32/lib/ffi/library.rb:254:in `attach_function'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/czmq-ffi-gen-0.12.0-x64-mingw32/lib/czmq-ffi-gen/czmq/ffi.rb:1069:in `<module:FFI>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/czmq-ffi-gen-0.12.0-x64-mingw32/lib/czmq-ffi-gen/czmq/ffi.rb:10:in `<module:CZMQ>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/czmq-ffi-gen-0.12.0-x64-mingw32/lib/czmq-ffi-gen/czmq/ffi.rb:9:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/czmq-ffi-gen-0.12.0-x64-mingw32/lib/czmq-ffi-gen.rb:2:in `require_relative'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/czmq-ffi-gen-0.12.0-x64-mingw32/lib/czmq-ffi-gen.rb:2:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cztop-0.11.2/lib/cztop.rb:1:in `<top (required)>
```

It's a bug of Ruby bindings provided by CZMQ. `uint64` instead of `uint64_t` should be used.

I've fixed it in CZMQ (zeromq/czmq#1582). Could you update submodulel-ed CZMQ revision and release a new version?

**Comment by paddor** [comment]
Cool! I'll make a release later today. :)

**Comment by kou** [comment]
Thanks!

**Comment by paddor** [comment]
Done. You can give it a try :)
