### ISSUE TITLE
CZMQ Generated Ruby Bindings not Packaged into Gem

### ISSUE THREAD

**Issue by Jared-Prime** [paddor/czmq-ffi-gen#8]
I get an error when trying to run code using `cztop`:

```
/usr/local/bundle/gems/ffi-1.9.18/lib/ffi/library.rb:176:in `ffi_libraries': no library specified (LoadError)
	from /usr/local/bundle/gems/ffi-1.9.18/lib/ffi/library.rb:254:in `attach_function'
	from /usr/local/bundle/gems/czmq-ffi-gen-0.13.0/lib/czmq-ffi-gen/signals.rb:4:in `<module:FFI>'
	from /usr/local/bundle/gems/czmq-ffi-gen-0.13.0/lib/czmq-ffi-gen/signals.rb:2:in `<module:CZMQ>'
	from /usr/local/bundle/gems/czmq-ffi-gen-0.13.0/lib/czmq-ffi-gen/signals.rb:1:in `<top (required)>'
	from /usr/local/bundle/gems/czmq-ffi-gen-0.13.0/lib/czmq-ffi-gen.rb:5:in `require_relative'
	from /usr/local/bundle/gems/czmq-ffi-gen-0.13.0/lib/czmq-ffi-gen.rb:5:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/cztop-0.11.4/lib/cztop.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /opt/apps/beelining/lib/zmq_examples/synchronous.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./bin/synchronous-example.rb:3:in `<main>'
```

I _think_ this is because the [symlink](https://github.com/paddor/czmq-ffi-gen/blob/master/lib/czmq-ffi-gen/czmq) to the vendorized bindings leads to nowhere. When I look at the installed gems, I see that the generated bindings for CZMQ Ruby are not placed in `vendor/cache` for the gem:

```
../
./
lib/
AUTHORS
CHANGES.md
Gemfile
LICENSE
README.md
```

Do I have the library configured correctly, or does the project need to package the dependent bindings?

**Comment by Jared-Prime** [comment]
this is actually due to my `czmq` installation placed in `/usr/local/czmq-4.0.2/src/.libs/libczmq.so` rather than `/usr/local/lib/libczmq.so`. The gem loads the library correctly if it's in the expected path.
